n = -10:10;
y0 = pb3(n);
y1 = pb3(-1.*n);
y2 = pb3(2 - n);
y3 = pb3(2.*n);
y4 = pb3(n./2);
subplot(321); stem(n,y0);
ylabel("g[{\itn}]", "FontName","Times");
xlabel("\itn", "FontName","Times");
subplot(322); stem(n,y1);
ylabel("g[{-\itn}]", "FontName","Times");
xlabel("\itn", "FontName","Times");
subplot(323); stem(n,y2);
ylabel("g[{2-\itn}]", "FontName","Times");
xlabel("\itn", "FontName","Times");
subplot(324); stem(n,y3);
ylabel("g[2{\itn}]", "FontName","Times");
xlabel("\itn", "FontName","Times");
subplot(325); stem(n,y4);
ylabel("g[{\itn}/2]", "FontName","Times");
xlabel("\itn", "FontName","Times");
